#!/usr/bin/env python

from table2ascii import table2ascii as t2a, PresetStyle, Alignment


def alignment(column: str):
    if column.strip().count(":") == 2:
        return Alignment.CENTER

    if column.strip().index(":") == 0:
        return Alignment.LEFT

    return Alignment.RIGHT


lines = []

print("Markdown table :")

while (line := input()) != "":
    lines.append(line)


table = t2a(
    header=[column.strip() for column in lines[0][1:-1].split("|")],
    body=[[column.strip() for column in line[1:-1].split("|")] for line in lines[2:]],
    style=PresetStyle.thin_compact,
    alignments=[alignment(column) for column in lines[1][1:-1].split("|")],
)

print(f"ASCII table :\n{table}")
